import { defineProducts } from '@forgewp/woocommerce';

export const products = defineProducts([
  {
    id: 1,
    slug: 'minimalist-wool-blazer',
    name: 'Minimalist Wool Blazer',
    title: 'Minimalist Wool Blazer',
    price: 285,
    regular_price: 285,
    currency: 'USD',
    images: [
      '/wool_blazer_beige.jpg',
      '/wool_blazer_matte_noir.jpg',
      '/wool_blazer_olive_sage.jpg',
    ],
    featuredImage: '/wool_blazer_beige.jpg',
    category: 'Outerwear',
    categorySlug: 'outerwear',
    categories: ['Outerwear', 'Tailoring', 'Blazers'],
    tags: ['wool', 'tailoring', 'outerwear', 'minimalist'],
    rating: 4.9,
    average_rating: 4.9,
    reviewCount: 24,
    rating_count: 24,
    badge: 'Trending',
    shortDescription: 'Tailored single-breasted wool blazer with clean lines and relaxed drape.',
    excerpt: 'Tailored single-breasted wool blazer with clean lines and relaxed drape.',
    description: 'Constructed from sustainably sourced Italian virgin wool, this minimalist blazer features structured natural shoulders, horn button detailing, and a breathable cupro lining. Designed for seamless transitions from studio to evening.',
    content: '<p>Constructed from sustainably sourced Italian virgin wool, this minimalist blazer features structured natural shoulders, horn button detailing, and a breathable cupro lining. Designed for seamless transitions from studio to evening.</p>',
    materials: ['100% Virgin Italian Wool', '100% Bemberg Cupro Lining'],
    dimensions: { length: 76, width: 50, height: 4, unit: 'cm' },
    weight: 0.85,
    care: 'Dry clean only. Store on shaped wooden hanger.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'beige', label: 'Sand Beige', value: 'beige', color: '#D6C7B2' },
          { id: 'noir', label: 'Matte Noir', value: 'noir', color: '#2B2B2A' },
          { id: 'sage', label: 'Olive Sage', value: 'sage', color: '#5A6251' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-BLZ-01',
    brand: 'Forge Commerce',
  },
  {
    id: 2,
    slug: 'classic-trench-coat',
    name: 'Classic Trench Coat',
    title: 'Classic Trench Coat',
    price: 340,
    regular_price: 420,
    sale_price: 340,
    currency: 'USD',
    images: [
      '/trench_camel_khaki.jpg',
      '/trench_bone_white.jpg',
    ],
    featuredImage: '/trench_camel_khaki.jpg',
    category: 'Outerwear',
    categorySlug: 'outerwear',
    categories: ['Outerwear', 'Coats'],
    tags: ['trench', 'waterproof', 'outerwear', 'classic'],
    rating: 4.8,
    average_rating: 4.8,
    reviewCount: 42,
    rating_count: 42,
    badge: 'Sale',
    shortDescription: 'Double-breasted weather-resistant cotton gabardine trench coat.',
    excerpt: 'Double-breasted weather-resistant cotton gabardine trench coat.',
    description: 'An archival silhouette re-engineered for modern climates. Features water-repellent dense cotton gabardine weave, storm flap, waist-cinching buckle belt, and deep welt pockets.',
    content: '<p>An archival silhouette re-engineered for modern climates. Features water-repellent dense cotton gabardine weave, storm flap, waist-cinching buckle belt, and deep welt pockets.</p>',
    materials: ['100% Organic Cotton Gabardine', 'Tortoise Acetate Buckles'],
    dimensions: { length: 115, width: 56, height: 5, unit: 'cm' },
    weight: 1.2,
    care: 'Dry clean or gentle hand wipe.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'khaki', label: 'Camel Khaki', value: 'khaki', color: '#CBB49A' },
          { id: 'bone', label: 'Bone White', value: 'bone', color: '#ECE9E2' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-TRN-02',
    brand: 'Forge Commerce',
  },
  {
    id: 3,
    slug: 'cashmere-ribbed-turtleneck',
    name: 'Cashmere Ribbed Turtleneck',
    title: 'Cashmere Ribbed Turtleneck',
    price: 195,
    regular_price: 195,
    currency: 'USD',
    images: [
      '/turtleneck_alabaster.jpg',
      '/turtleneck_cocoa.jpg',
    ],
    featuredImage: '/turtleneck_alabaster.jpg',
    category: 'Knitwear',
    categorySlug: 'knitwear',
    categories: ['Knitwear', 'Sweaters', 'Tops'],
    tags: ['cashmere', 'turtleneck', 'knitwear', 'warmth'],
    rating: 4.95,
    average_rating: 4.95,
    reviewCount: 56,
    rating_count: 56,
    badge: 'Essential',
    shortDescription: 'Grade-A Mongolian cashmere knit with wide fold neck and elongated cuffs.',
    excerpt: 'Grade-A Mongolian cashmere knit with wide fold neck and elongated cuffs.',
    description: 'Spun from long-staple organic Mongolian cashmere fibers to minimize pilling while offering unmatched featherweight warmth and cloud-like softness against the skin.',
    content: '<p>Spun from long-staple organic Mongolian cashmere fibers to minimize pilling while offering unmatched featherweight warmth and cloud-like softness against the skin.</p>',
    materials: ['100% Grade-A Mongolian Cashmere (2-ply 12-gauge)'],
    dimensions: { length: 68, width: 48, height: 3, unit: 'cm' },
    weight: 0.38,
    care: 'Hand wash cold with wool detergent or dry clean.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'alabaster', label: 'Alabaster', value: 'alabaster', color: '#EDEAE4' },
          { id: 'cocoa', label: 'Deep Cocoa', value: 'cocoa', color: '#5C4033' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-KNT-03',
    brand: 'Forge Commerce',
  },
  {
    id: 4,
    slug: 'oversized-wool-cardigan',
    name: 'Oversized Wool Cardigan',
    title: 'Oversized Wool Cardigan',
    price: 225,
    regular_price: 225,
    currency: 'USD',
    images: [
      '/cardigan_cedar.jpg',
      '/cardigan_grey.jpg',
    ],
    featuredImage: '/cardigan_cedar.jpg',
    category: 'Knitwear',
    categorySlug: 'knitwear',
    categories: ['Knitwear', 'Sweaters', 'Cardigans'],
    tags: ['cardigan', 'wool', 'oversized', 'layering'],
    rating: 4.88,
    average_rating: 4.88,
    reviewCount: 31,
    rating_count: 31,
    badge: 'New',
    shortDescription: 'Heavy-knit chunky cardigan with dropped shoulders and natural horn buttons.',
    excerpt: 'Heavy-knit chunky cardigan with dropped shoulders and natural horn buttons.',
    description: 'A relaxed silhouette designed for comfortable layering. Knitted from undyed Shetland wool that gains character and softness with every season.',
    content: '<p>A relaxed silhouette designed for comfortable layering. Knitted from undyed Shetland wool that gains character and softness with every season.</p>',
    materials: ['100% Shetland Wool', 'Genuine Horn Buttons'],
    dimensions: { length: 72, width: 58, height: 5, unit: 'cm' },
    weight: 0.72,
    care: 'Hand wash cold. Lay flat to dry.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'cedar', label: 'Warm Cedar', value: 'cedar', color: '#7C6A58' },
          { id: 'heather', label: 'Heather Grey', value: 'heather', color: '#2C2A29' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-KNT-04',
    brand: 'Forge Commerce',
  },
  {
    id: 5,
    slug: 'moss-melange-crewneck',
    name: 'Moss Melange Crewneck',
    title: 'Moss Melange Crewneck',
    price: 180,
    regular_price: 180,
    currency: 'USD',
    images: [
      '/sweater_moss_melange.jpg',
      '/sweater_earth_brown.jpg',
      '/sweater_vanilla_cream.jpg',
    ],
    featuredImage: '/sweater_moss_melange.jpg',
    category: 'Knitwear',
    categorySlug: 'knitwear',
    categories: ['Knitwear', 'Sweaters', 'Tops'],
    tags: ['crewneck', 'merino', 'knitwear', 'earth-tones'],
    rating: 4.9,
    average_rating: 4.9,
    reviewCount: 19,
    rating_count: 19,
    badge: 'Curator Pick',
    shortDescription: 'Extra-fine merino wool crewneck knitted with subtle multi-tonal yarn.',
    excerpt: 'Extra-fine merino wool crewneck knitted with subtle multi-tonal yarn.',
    description: 'Spun from sustainably sheared Australian extra-fine merino wool, featuring seamless ribbing along the collar, hem, and cuffs for optimal shape retention.',
    content: '<p>Spun from sustainably sheared Australian extra-fine merino wool, featuring seamless ribbing along the collar, hem, and cuffs for optimal shape retention.</p>',
    materials: ['100% Extra-Fine Merino Wool (19.5 micron)'],
    dimensions: { length: 67, width: 50, height: 3, unit: 'cm' },
    weight: 0.42,
    care: 'Dry clean or cold wool wash.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'moss', label: 'Moss Melange', value: 'moss', color: '#5A6251' },
          { id: 'earth', label: 'Earth Brown', value: 'earth', color: '#5C4033' },
          { id: 'vanilla', label: 'Vanilla Cream', value: 'vanilla', color: '#EDEAE4' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-KNT-05',
    brand: 'Forge Commerce',
  },
  {
    id: 6,
    slug: 'structured-charcoal-overcoat',
    name: 'Structured Charcoal Overcoat',
    title: 'Structured Charcoal Overcoat',
    price: 360,
    regular_price: 360,
    currency: 'USD',
    images: [
      '/wool_coat_charcoal.jpg',
      '/wool_coat_desert_taupe.jpg',
      '/wool_coat_oatmeal.jpg',
    ],
    featuredImage: '/wool_coat_charcoal.jpg',
    category: 'Outerwear',
    categorySlug: 'outerwear',
    categories: ['Outerwear', 'Coats'],
    tags: ['coat', 'heavyweight', 'outerwear', 'tailored'],
    rating: 4.92,
    average_rating: 4.92,
    reviewCount: 38,
    rating_count: 38,
    badge: 'Best Seller',
    shortDescription: 'Heavyweight double-faced wool overcoat with sharp notch lapels.',
    excerpt: 'Heavyweight double-faced wool overcoat with sharp notch lapels.',
    description: 'Expertly tailored from 650gsm Melton wool with deep thermal insulation, back vent for fluid movement, and concealed internal passport pocket.',
    content: '<p>Expertly tailored from 650gsm Melton wool with deep thermal insulation, back vent for fluid movement, and concealed internal passport pocket.</p>',
    materials: ['85% Melton Wool, 15% Recycled Cashmere', 'Cupro Jacquard Lining'],
    dimensions: { length: 110, width: 54, height: 6, unit: 'cm' },
    weight: 1.45,
    care: 'Dry clean only.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'charcoal', label: 'Charcoal Noir', value: 'charcoal', color: '#2C2A29' },
          { id: 'taupe', label: 'Desert Taupe', value: 'taupe', color: '#A38E7A' },
          { id: 'oatmeal', label: 'Oatmeal', value: 'oatmeal', color: '#EDEAE4' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-OUT-06',
    brand: 'Forge Commerce',
  },
  {
    id: 7,
    slug: 'classic-ribbed-beanie',
    name: 'Classic Ribbed Beanie',
    title: 'Classic Ribbed Beanie',
    price: 65,
    regular_price: 65,
    currency: 'USD',
    images: [
      '/beanie_charcoal.jpg',
      '/beanie_forest_sage.jpg',
      '/beanie_oatmeal.jpg',
    ],
    featuredImage: '/beanie_charcoal.jpg',
    category: 'Accessories',
    categorySlug: 'accessories',
    categories: ['Accessories', 'Knitwear', 'Hats'],
    tags: ['beanie', 'cashmere', 'accessories', 'winter'],
    rating: 4.96,
    average_rating: 4.96,
    reviewCount: 68,
    rating_count: 68,
    badge: 'Essential',
    shortDescription: 'Ultra-soft organic cashmere ribbed beanie with fold-over cuff.',
    excerpt: 'Ultra-soft organic cashmere ribbed beanie with fold-over cuff.',
    description: 'A daily cold-weather staple knitted from ultra-soft organic cashmere. Features an insulating wide rib weave and versatile fold-over cuff designed for snug, comfortable fit.',
    content: '<p>A daily cold-weather staple knitted from ultra-soft organic cashmere. Features an insulating wide rib weave and versatile fold-over cuff designed for snug, comfortable fit.</p>',
    materials: ['100% Organic Cashmere'],
    dimensions: { length: 22, width: 20, height: 2, unit: 'cm' },
    weight: 0.08,
    care: 'Hand wash cold with mild wool shampoo.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'charcoal', label: 'Charcoal', value: 'charcoal', color: '#2C2A29' },
          { id: 'sage', label: 'Forest Sage', value: 'sage', color: '#5A6251' },
          { id: 'oatmeal', label: 'Oatmeal', value: 'oatmeal', color: '#E8E2D9' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-ACC-07',
    brand: 'Forge Commerce',
  },
  {
    id: 8,
    slug: 'chunky-fringe-scarf',
    name: 'Chunky Fringe Scarf',
    title: 'Chunky Fringe Scarf',
    price: 95,
    regular_price: 95,
    currency: 'USD',
    images: [
      '/scarf_desert_sand.jpg',
      '/scarf_moss_green.jpg',
    ],
    featuredImage: '/scarf_desert_sand.jpg',
    category: 'Accessories',
    categorySlug: 'accessories',
    categories: ['Accessories', 'Knitwear', 'Scarves'],
    tags: ['scarf', 'fringe', 'wool', 'accessories'],
    rating: 4.85,
    average_rating: 4.85,
    reviewCount: 22,
    rating_count: 22,
    badge: 'Popular',
    shortDescription: 'Generously proportioned brushed alpaca-blend scarf with twisted fringe.',
    excerpt: 'Generously proportioned brushed alpaca-blend scarf with twisted fringe.',
    description: 'Crafted from a plush blend of royal alpaca and merino wool, brushed for a cloud-like fuzzy texture that provides effortless warmth and dramatic drape.',
    content: '<p>Crafted from a plush blend of royal alpaca and merino wool, brushed for a cloud-like fuzzy texture that provides effortless warmth and dramatic drape.</p>',
    materials: ['70% Royal Baby Alpaca, 30% Fine Merino Wool'],
    dimensions: { length: 220, width: 45, height: 2, unit: 'cm' },
    weight: 0.34,
    care: 'Dry clean or gentle steam.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'sand', label: 'Desert Sand', value: 'sand', color: '#D6C7B2' },
          { id: 'moss', label: 'Moss Green', value: 'moss', color: '#5A6251' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-ACC-08',
    brand: 'Forge Commerce',
  },
  {
    id: 9,
    slug: 'saddle-leather-gloves',
    name: 'Saddle Leather Gloves',
    title: 'Saddle Leather Gloves',
    price: 120,
    regular_price: 120,
    currency: 'USD',
    images: [
      '/leather_gloves_saddle_tan.jpg',
      '/leather_gloves_matte_black.jpg',
    ],
    featuredImage: '/leather_gloves_saddle_tan.jpg',
    category: 'Accessories',
    categorySlug: 'accessories',
    categories: ['Accessories', 'Leather', 'Gloves'],
    tags: ['leather', 'gloves', 'cashmere-lined', 'accessories'],
    rating: 4.91,
    average_rating: 4.91,
    reviewCount: 17,
    rating_count: 17,
    badge: 'Handcrafted',
    shortDescription: 'Supple lambskin leather gloves fully lined in 100% pure cashmere.',
    excerpt: 'Supple lambskin leather gloves fully lined in 100% pure cashmere.',
    description: 'Hand-stitched by master glovemakers using full-grain Italian lamb nappa leather. Features conductive touch-screen fingertips and pure cashmere inner lining for refined warmth.',
    content: '<p>Hand-stitched by master glovemakers using full-grain Italian lamb nappa leather. Features conductive touch-screen fingertips and pure cashmere inner lining for refined warmth.</p>',
    materials: ['100% Italian Lamb Nappa Leather', '100% Cashmere Lining'],
    dimensions: { length: 24, width: 11, height: 2, unit: 'cm' },
    weight: 0.14,
    care: 'Specialist leather clean only.',
    attributes: [
      {
        name: 'Color',
        variation: true,
        options: [
          { id: 'tan', label: 'Saddle Tan', value: 'tan', color: '#A3734C' },
          { id: 'black', label: 'Matte Black', value: 'black', color: '#1E1E1E' },
        ],
      },
    ],
    inStock: true,
    stock_status: 'instock',
    manage_stock: false,
    sku: 'FC-ACC-09',
    brand: 'Forge Commerce',
  },
]);

export default products;
