import { copyFileSync, cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * @param {Object} options
 * @param {string} options.themeRoot
 * @param {string} options.outDir
 * @param {import('./types.js').ForgeWPThemeConfig} options.config
 * @param {string} options.appHtml
 * @param {string} [options.headerHtml]
 * @param {string} [options.footerHtml]
 * @param {import('./types.js').ForgeWPBuildAssets} options.assets
 */
export function generateTheme({
  themeRoot,
  outDir,
  config,
  appHtml,
  headerHtml = "",
  footerHtml = "",
  assets,
}) {
  if (existsSync(outDir)) {
    rmSync(outDir, { recursive: true, force: true });
  }

  mkdirSync(outDir, { recursive: true });

  const assetsOut = path.join(outDir, "assets");
  const distAssets = path.join(themeRoot, "dist", "assets");
  mkdirSync(assetsOut, { recursive: true });
  cpSync(distAssets, assetsOut, { recursive: true });

  // Drop unused JS from the theme ZIP
  import("node:fs").then(({ readdirSync, unlinkSync }) => {
    const files = readdirSync(assetsOut);
    for (const file of files) {
      if (file.endsWith(".js") || file.endsWith(".js.map")) {
        unlinkSync(path.join(assetsOut, file));
      }
    }
  });

  // Fix nav links and split markup
  const processedApp = processMarkup(appHtml);
  const processedHeader = processMarkup(headerHtml);
  const processedFooter = processMarkup(footerHtml);

  // Extract content (App markup minus Header/Footer)
  let contentHtml = processedApp;
  if (processedHeader) {
    contentHtml = contentHtml.replace(processedHeader, "");
  }
  if (processedFooter) {
    contentHtml = contentHtml.replace(processedFooter, "");
  }

  const staticDir = path.join(outDir, "forgewp-static");
  mkdirSync(staticDir, { recursive: true });
  writeFileSync(path.join(staticDir, "content.html"), contentHtml, "utf8");
  writeFileSync(path.join(staticDir, "header.html"), processedHeader, "utf8");
  writeFileSync(path.join(staticDir, "footer.html"), processedFooter, "utf8");

  writeFileSync(path.join(outDir, "style.css"), buildStyleCss(config), "utf8");
  writeFileSync(
    path.join(outDir, "functions.php"),
    buildFunctionsPhp(config, assets),
    "utf8",
  );
  writeFileSync(path.join(outDir, "header.php"), buildHeaderPhp(config), "utf8");
  writeFileSync(path.join(outDir, "footer.php"), buildFooterPhp(config), "utf8");
  writeFileSync(path.join(outDir, "index.php"), buildIndexPhp(), "utf8");
  writeFileSync(path.join(outDir, "single.php"), buildSinglePhp(), "utf8");
  writeFileSync(path.join(outDir, "front-page.php"), buildIndexPhp(), "utf8");

  const themeJsonSrc = path.join(themeRoot, "wordpress", "theme.json");
  if (existsSync(themeJsonSrc)) {
    copyFileSync(themeJsonSrc, path.join(outDir, "theme.json"));
  }

  const screenshot = path.join(themeRoot, "wordpress", "screenshot.png");
  if (existsSync(screenshot)) {
    copyFileSync(screenshot, path.join(outDir, "screenshot.png"));
  }
}

/**
 * Process markup: fix nav links etc.
 */
function processMarkup(html) {
  if (!html) return "";
  // Fix nav links — # → <?php echo esc_url( home_url( '/' ) ); ?>
  // We use a placeholder and replace it in the PHP file generation if needed,
  // but for now we'll do it via string replacement in the template files.
  let processed = html.replace(
    /href="#"/g,
    'href="<?php echo esc_url( home_url( \'/\' ) ); ?>"',
  );

  processed = processed.replace(
    /__FORGEWP_THE_TITLE__/g,
    '<?php the_title(); ?>'
  );

  processed = processed.replace(
    /__FORGEWP_THE_CONTENT__/g,
    '<?php the_content(); ?>'
  );

  processed = processed.replace(
    /__FORGEWP_THE_PERMALINK__/g,
    '<?php the_permalink(); ?>'
  );

  processed = processed.replace(
    /__FORGEWP_THE_EXCERPT__/g,
    '<?php the_excerpt(); ?>'
  );

  processed = processed.replace(
    /<forgewp-loop-start\s*\/?>/g,
    '<?php if (have_posts()) : while (have_posts()) : the_post(); ?>'
  );

  processed = processed.replace(
    /<forgewp-loop-end\s*\/?>/g,
    '<?php endwhile; else : echo "<p>No posts found.</p>"; endif; ?>'
  );

  return processed;
}

/**
 * @param {import('./types.js').ForgeWPThemeConfig} config
 */
function buildStyleCss(config) {
  return `/*
Theme Name: ${config.name}
Theme URI: https://forgewp.dev
Author: ForgeWP
Description: ${config.description}
Version: ${config.version}
Requires at least: 6.0
Tested up to: 6.7
Requires PHP: 7.4
License: GNU General Public License v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${config.textDomain}
*/

/* Compiled styles are enqueued from assets/ via functions.php */
`;
}

/**
 * @param {import('./types.js').ForgeWPThemeConfig} config
 * @param {import('./types.js').ForgeWPBuildAssets} assets
 */
function buildFunctionsPhp(config, assets) {
  const css = assets.cssFile.replace(/^assets\//, "");
  const version = config.version.replace(/'/g, "\\'");

  return `<?php
/**
 * ${config.name} — generated by ForgeWP
 *
 * @package ${config.textDomain}
 */

if (! defined('ABSPATH')) {
    exit;
}

define('FORGEWP_THEME_VERSION', '${version}');

/**
 * Enqueue compiled theme assets (CSS only in v1 — static HTML, no hydration).
 */
function forgewp_enqueue_assets(): void {
    $theme_uri = get_template_directory_uri();
    $css_path = get_template_directory() . '/assets/${css}';

    if (file_exists($css_path)) {
        wp_enqueue_style(
            '${config.textDomain}-app',
            $theme_uri . '/assets/${css}',
            array(),
            FORGEWP_THEME_VERSION
        );
    }
}
add_action('wp_enqueue_scripts', 'forgewp_enqueue_assets');

/**
 * Theme supports.
 */
function forgewp_theme_setup(): void {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script'));
    add_theme_support('wp-block-styles');
    add_theme_support('editor-styles');
}
add_action('after_setup_theme', 'forgewp_theme_setup');
`;
}

function buildHeaderPhp(config) {
  return `<?php
/**
 * Theme header
 *
 * @package ${config.textDomain}
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php wp_head(); ?>
  <style>
    /* Reset WP link underlines to match React/Tailwind expected styling */
    a { text-decoration: none !important; }
    a:hover { text-decoration: none !important; }
  </style>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<?php
$header_file = get_template_directory() . '/forgewp-static/header.html';
if (file_exists($header_file)) {
    include $header_file;
}
?>
`;
}

function buildFooterPhp(config) {
  return `<?php
/**
 * Theme footer
 *
 * @package ${config.textDomain}
 */
$footer_file = get_template_directory() . '/forgewp-static/footer.html';
if (file_exists($footer_file)) {
    include $footer_file;
}
wp_footer();
?>
</body>
</html>
`;
}

function buildIndexPhp() {
  return `<?php
/**
 * Main template — displays ForgeWP compiled static markup
 *
 * @package forgewp
 */

get_header();

$markup_file = get_template_directory() . '/forgewp-static/content.html';

if (is_front_page() && file_exists($markup_file)) {
    include $markup_file;
} elseif (have_posts()) {
    echo '<main class="mx-auto max-w-3xl px-6 py-12">';
    while (have_posts()) {
        the_post();
        echo '<article class="mb-12">';
        echo '<h1 class="text-3xl font-bold mb-4">' . get_the_title() . '</h1>';
        echo '<div class="prose prose-zinc max-w-none">';
        the_content();
        echo '</div>';
        echo '</article>';
    }
    echo '</main>';
}

get_footer();
`;
}

function buildSinglePhp() {
  return `<?php
/**
 * Single post template
 *
 * @package forgewp
 */

get_header();

if (have_posts()) {
    while (have_posts()) {
        the_post();
        echo '<main class="mx-auto max-w-3xl px-6 py-12">';
        echo '<article>';
        echo '<h1 class="text-4xl font-bold mb-6">' . get_the_title() . '</h1>';
        echo '<div class="prose prose-zinc max-w-none">';
        the_content();
        echo '</div>';
        echo '</article>';
        echo '</main>';
    }
}

get_footer();
`;
}
